### ISSUE TITLE
invalid memory address or nil pointer dereference when using driver.WithReleaseConnection() in PrepareBatch

### ISSUE THREAD

**Issue by nityanandagohain** [ClickHouse/clickhouse-go#1167]
### Steps to reproduce
1. PrepareBatch with `driver.WithReleaseConnection()`
2. Wait for the deadline to exceed by adding a delay before executing the `.Send()` statement.

### Expected behaviour
* It should just return the error instead of panic

### Error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4806b5c]

goroutine 612 [running]:
github.com/ClickHouse/clickhouse-go/v2.(*batch).Send.func1()
	/home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.15.0/conn_batch.go:184 +0x1c
github.com/ClickHouse/clickhouse-go/v2.contextWatchdog.func1()
	/home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.15.0/context_watchdog.go:39 +0x48
created by github.com/ClickHouse/clickhouse-go/v2.contextWatchdog
	/home/runner/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.15.0/context_watchdog.go:33 +0xbe
```

**Comment by jkaflik** [comment]
Thanks for reporting & submitting a patch. This fix will be released today.
