### ISSUE TITLE
Panic occurs but is never thrown when inserting a nil value in a Map() column

### ISSUE THREAD

**Issue by peter-uxify** [ClickHouse/clickhouse-go#1371]
## Observed

1. Inserting a nil value into a column of type `Map()` results in a silent panic that never bubbles up. The go routine remains stuck and the error cannot be detected without tools like pprof.

## Expected behaviour
An error to be returned. Just like attempting to insert an `int` results in `converting int to Map(LowCardinality(String), String) is unsupported. try using map[string]string`

## Code example

```go
package main

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

func main() {
	var db *sql.DB
	db, _ = clickhouse.GetConnection() // implementation not shown here
	conn, err := db.Conn(context.Background())
	if err != nil {
		fmt.Println(err)
		return
	}
	defer conn.Close()

	tx, err := conn.BeginTx(context.Background(), nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer tx.Rollback()

	columns := []string{
		"num",
		"map1",
		"map2",
	}
	row := []interface{}{
		1,
		map[string]string{"a": "b"},
		nil, // if it were an empty map[string]string{}, it would pass. If it were an int, it would result in "converting int to Map(LowCardinality(String), String) is unsupported. try using map[string]string"
	}
	sql := fmt.Sprintf(
		"INSERT INTO %s (%s) VALUES ",
		"mytable",
		strings.Join(columns, ","),
	)

	stmt, err := tx.Prepare(sql)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer stmt.Close()

	fmt.Println("Executing...")
	_, err = stmt.Exec(row...) // this is where it gets stuck
	if err != nil {
		fmt.Println(err)
		return
	}

	err = tx.Commit()

	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("Success! (this will never be printed)")
}
```

## Error log

```stack trace
goroutine 26 [sync.RWMutex.Lock, 3 minutes]:
sync.runtime_SemacquireRWMutex(0x65a8e0?, 0x40?, 0x0?)
	/usr/local/go/src/runtime/sema.go:87 +0x28
sync.(*RWMutex).Lock(0x40001e3328?)
	/usr/local/go/src/sync/rwmutex.go:151 +0xf8
database/sql.(*Tx).rollback(0x4000022280, 0x0)
	/usr/local/go/src/database/sql/sql.go:2330 +0xac
database/sql.(*Tx).Rollback(...)
	/usr/local/go/src/database/sql/sql.go:2349
panic({0x481e40?, 0x4000202150?})
	/usr/local/go/src/runtime/panic.go:770 +0x124
reflect.Value.typeSlow({0x0?, 0x0?, 0x40001e3400?})
	/usr/local/go/src/reflect/value.go:2699 +0x134
reflect.Value.Type(...)
	/usr/local/go/src/reflect/value.go:2694
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Map).AppendRow(0x400012a400, {0x0, 0x0})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.26.0/lib/column/map.go:173 +0xf4
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Append(0x4000030580, {0x400055aa08?, 0x6a, 0xffff00023f35?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.26.0/lib/proto/block.go:62 +0x16c
github.com/ClickHouse/clickhouse-go/v2.(*httpBatch).Append(0x700000100010001?, {0x400055aa08?, 0x6f8?, 0xffffb1ff0a68?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.26.0/conn_http_batch.go:142 +0x2c
github.com/ClickHouse/clickhouse-go/v2.(*stdBatch).Exec(0x4000202138, {0x400055a308, 0x6a, 0xffff681e1c38?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.26.0/clickhouse_std.go:361 +0x108
github.com/ClickHouse/clickhouse-go/v2.(*stdBatch).ExecContext(0x4000202138, {0x4ba640?, 0x40000c3308?}, {0x40000c3308, 0x6a, 0x570a8?})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.26.0/clickhouse_std.go:373 +0x114
database/sql.ctxDriverStmtExec({0x65e5a8, 0xa1c880}, {0x65e9d0, 0x4000202138}, {0x40000c3308, 0x6a, 0x6a?})
	/usr/local/go/src/database/sql/ctxutil.go:65 +0x9c
database/sql.resultFromStatement({0x65e5a8, 0xa1c880}, {0x65e4e0, 0x40001467e0}, 0x40000311c0, {0x4000130e08, 0x6a, 0x6a})
	/usr/local/go/src/database/sql/sql.go:2670 +0xe0
database/sql.(*Stmt).ExecContext.func1(0x0?)
	/usr/local/go/src/database/sql/sql.go:2644 +0x8c
database/sql.(*DB).retry(0x99ed60?, 0x40001e3ab0)
	/usr/local/go/src/database/sql/sql.go:1566 +0x4c
database/sql.(*Stmt).ExecContext(0x65a8c0?, {0x65e5a8?, 0xa1c880?}, {0x4000130e08?, 0x40001e3dd8?, 0x2?})
	/usr/local/go/src/database/sql/sql.go:2638 +0x12c
database/sql.(*Stmt).Exec(...)
	/usr/local/go/src/database/sql/sql.go:2658
...
```

### Environment
* [x] `clickhouse-go` version: `v2.26.0`
* [x] Interface: `database/sql`
* [x] Go version: `1.22.6 linux/arm64`
* [x] Operating system: Linux docker container under both Linux and MacOS
* [x] ClickHouse version: `24.6.3.78`
* [x] `CREATE TABLE` statements for tables involved:
```
CREATE TABLE mytable
ON CLUSTER default
(
    `num` UInt8 DEFAULT 0,
    `map1` Map(LowCardinality(String), String) DEFAULT map(),
    `map2` Map(LowCardinality(String), String) DEFAULT map(),
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test/mytable', '{replica}')
ORDER BY(num)
SETTINGS index_granularity = 8192
```

**Comment by jkaflik** [comment]
@peter-uxify thanks for reporting.
