### ISSUE TITLE
Alter table Drop Partition hangs reading from Clickhouse

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/clickhouse-go#202]
Not sure what's going on but it looks like it's stuck reading from the network.

Using version: 1d87030de2a38bbe8c05e1b13f5b2f27466fd5a8

Connected to ClickHouse server version 19.9.2 revision 54421.

This looks related: https://github.com/kshvakov/clickhouse/commit/4ca5dc1073e63661819d546d662ac8c19848e42d

```
^\SIGQUIT: quit
PC=0x45b103 m=0 sigcode=128

goroutine 9 [syscall]:
runtime.notetsleepg(0xb0eee0, 0xdf8470cfe, 0x1414)
        /usr/lib/go/src/runtime/lock_futex.go:227 +0x34 fp=0xc000039f60 sp=0xc000039f30 pc=0x40c014
runtime.timerproc(0xb0eec0)
        /usr/lib/go/src/runtime/time.go:311 +0x2ea fp=0xc000039fd8 sp=0xc000039f60 pc=0x44a9aa
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000039fe0 sp=0xc000039fd8 pc=0x4592a1
created by runtime.(*timersBucket).addtimerLocked
        /usr/lib/go/src/runtime/time.go:169 +0x10e

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fbee951b310, 0x72, 0xffffffffffffffff)
        /usr/lib/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000144618, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000144600, 0xc000170000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000144600, 0xc000170000, 0x1000, 0x1000, 0x528dbf, 0xc000144600, 0xc000170000)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000100f0, 0xc000170000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:177 +0x69
bufio.(*Reader).Read(0xc000061560, 0xc00005cd28, 0x1, 0xa, 0x2a6820a700, 0xb0b4e0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:223 +0x23e
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*connect).Read(0xc0000f63f0, 0xc00005cd28, 0x1, 0xa, 0x1, 0xa, 0x1)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/connect.go:105 +0xf7
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).ReadByte(0xc00005cd00, 0xc0000f63f0, 0x2a6820a700, 0xef)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:157 +0x59
encoding/binary.ReadUvarint(0x8762a0, 0xc00005cd00, 0xa, 0x1, 0x0)
        /usr/lib/go/src/encoding/binary/varint.go:110 +0x7b
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).Uvarint(...)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:43
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).String(0xc00005cd00, 0x0, 0x0, 0x0, 0x0)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:145 +0x3c
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*clickhouse).readBlock(0xc000144500, 0xc00005cd00, 0x5, 0x0)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/clickhouse_read_block.go:8 +0x33
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*clickhouse).readMeta(0xc000144500, 0xc00006a7e0, 0x53, 0x0)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/clickhouse_read_meta.go:45 +0x36d
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*stmt).queryContext(0xc000164360, 0x87d280, 0xc000018078, 0xb27738, 0x0, 0x0, 0x7a0e20, 0x7d1720, 0xc000018001, 0x7fbee94d6148)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/stmt.go:84 +0xf1
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*stmt).QueryContext(0xc000164360, 0x87d280, 0xc000018078, 0xb27738, 0x0, 0x0, 0x3, 0xc000141900, 0x42c38f, 0x8)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/stmt.go:75 +0x67
database/sql.ctxDriverStmtQuery(0x87d280, 0xc000018078, 0x87d440, 0xc000164360, 0xb27738, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/database/sql/ctxutil.go:82 +0x210
database/sql.rowsiFromStatement(0x87d280, 0xc000018078, 0x87c200, 0xc000144500, 0xc00005cd80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:2517 +0x159
database/sql.(*DB).queryDC(0xc0000d0180, 0x87d280, 0xc000018078, 0x0, 0x0, 0xc0000c6480, 0xc000023120, 0xc00006a5a0, 0x53, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:1570 +0x230
database/sql.(*DB).query(0xc0000d0180, 0x87d280, 0xc000018078, 0xc00006a5a0, 0x53, 0x0, 0x0, 0x0, 0xc00005cb00, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:1518 +0x136
database/sql.(*DB).QueryContext(0xc0000d0180, 0x87d280, 0xc000018078, 0xc00006a5a0, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:1501 +0x20f
github.com/segmentio/clickhouse-mon/internal/daemon.Retainer.Run(0xc0000169e0, 0x1d, 0xc000018822, 0x2, 0x19, 0x0, 0x87d280, 0xc000018078, 0xc0000d0180)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/internal/daemon/retention.go:78 +0x851
main.main()
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/cmd/drop-partitions/main.go:39 +0x38d

goroutine 5 [chan receive]:
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.init.0.func1()
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/bootstrap.go:44 +0x4c
created by github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.init.0
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/bootstrap.go:41 +0x74

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [select]:
database/sql.(*DB).connectionOpener(0xc0000d0180, 0x87d240, 0xc00005c840)
        /usr/lib/go/src/database/sql/sql.go:1000 +0xe8
created by database/sql.OpenDB
        /usr/lib/go/src/database/sql/sql.go:670 +0x15e

goroutine 8 [select]:
database/sql.(*DB).connectionResetter(0xc0000d0180, 0x87d240, 0xc00005c840)
        /usr/lib/go/src/database/sql/sql.go:1013 +0xfb
created by database/sql.OpenDB
        /usr/lib/go/src/database/sql/sql.go:671 +0x194

rax    0xfffffffffffffffc
rbx    0x3b9a7efe
rcx    0x45b103
rdx    0x0
rdi    0xb0eee0
rsi    0x80
rbp    0xc000039ee8
rsp    0xc000039ea0
r8     0x0
r9     0x0
r10    0xc000039ed8
r11    0x202
r12    0x1
r13    0xc00011c360
r14    0xc00011c420
r15    0x55
rip    0x45b103
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by abraithwaite** [comment]
Letting it run a little while longer (not sending SIGQUIT), I get this:

```
drop-partitions[22742]: 2019-08-07 22:43:41.198 - github.com/segmentio/clickhouse-mon/internal/daemon/retention.go:80 - retention: driver: bad connection
```

**Comment by abraithwaite** [comment]
Same behavior for version v1.3.10 (a5f69ea606622ffd124676fd0b7a9148426ad2b4)

```
^\SIGQUIT: quit
PC=0x45b2b0 m=0 sigcode=128

goroutine 0 [idle]:
runtime.epollwait(0x7fff00000004, 0x7fffbeca0500, 0xffffffff00000080, 0x16300000000, 0xffffffffbeca0499, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/runtime/sys_linux_amd64.s:675 +0x20
runtime.netpoll(0xc000026501, 0x1)
        /usr/lib/go/src/runtime/netpoll_epoll.go:71 +0x126
runtime.findrunnable(0xc000024000, 0x0)
        /usr/lib/go/src/runtime/proc.go:2380 +0x51f
runtime.schedule()
        /usr/lib/go/src/runtime/proc.go:2525 +0x21c
runtime.park_m(0xc000000180)
        /usr/lib/go/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x0)
        /usr/lib/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f4a64c14310, 0x72, 0xffffffffffffffff)
        /usr/lib/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000c6318, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000c6300, 0xc00012c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000c6300, 0xc00012c000, 0x1000, 0x1000, 0x528e3f, 0xc0000c6300, 0xc00012c000)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000a4008, 0xc00012c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:177 +0x69
bufio.(*Reader).Read(0xc000068360, 0xc0001320a8, 0x1, 0xa, 0xe7791f700, 0xb104e0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:223 +0x23e
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*connect).Read(0xc00012e000, 0xc0001320a8, 0x1, 0xa, 0x1, 0xa, 0x1)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/connect.go:142 +0xf7
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).ReadByte(0xc000132080, 0xc00012e000, 0xe7791f700, 0xef)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:157 +0x59
encoding/binary.ReadUvarint(0x879080, 0xc000132080, 0xa, 0x1, 0x0)
        /usr/lib/go/src/encoding/binary/varint.go:110 +0x7b
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).Uvarint(...)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:43
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).String(0xc000132080, 0x0, 0x0, 0x0, 0x0)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:145 +0x3c
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*clickhouse).readBlock(0xc0000c6200, 0xc000132080, 0x5, 0x0)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/clickhouse_read_block.go:8 +0x33
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*clickhouse).readMeta(0xc0000c6200, 0xc0000fc240, 0x53, 0x0)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/clickhouse_read_meta.go:45 +0x36d
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*stmt).queryContext(0xc000128960, 0x880020, 0xc000018078, 0xb2c738, 0x0, 0x0, 0x7a30c0, 0x7d3d00, 0xc000018001, 0x7f4a64bcf148)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/stmt.go:84 +0xf1
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.(*stmt).QueryContext(0xc000128960, 0x880020, 0xc000018078, 0xb2c738, 0x0, 0x0, 0x3, 0xc000141900, 0x42c38f, 0x8)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/stmt.go:75 +0x67
database/sql.ctxDriverStmtQuery(0x880020, 0xc000018078, 0x8801e0, 0xc000128960, 0xb2c738, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/database/sql/ctxutil.go:82 +0x210
database/sql.rowsiFromStatement(0x880020, 0xc000018078, 0x87efe0, 0xc0000c6200, 0xc000132400, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:2517 +0x159
database/sql.(*DB).queryDC(0xc0000d0180, 0x880020, 0xc000018078, 0x0, 0x0, 0xc000144000, 0xc000138220, 0xc0000fc120, 0x53, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:1570 +0x230
database/sql.(*DB).query(0xc0000d0180, 0x880020, 0xc000018078, 0xc0000fc120, 0x53, 0x0, 0x0, 0x0, 0xc000132301, 0xc0001288d0, ...)
        /usr/lib/go/src/database/sql/sql.go:1518 +0x136
database/sql.(*DB).QueryContext(0xc0000d0180, 0x880020, 0xc000018078, 0xc0000fc120, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:1495 +0xd1
database/sql.(*DB).Query(...)
        /usr/lib/go/src/database/sql/sql.go:1509
github.com/segmentio/clickhouse-mon/internal/daemon.Retainer.Run(0xc0000169e0, 0x1d, 0xc000018822, 0x2, 0x18, 0x0, 0x880020, 0xc000018078, 0xc0000d0180)
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/internal/daemon/retention.go:78 +0x851
main.main()
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/cmd/drop-partitions/main.go:39 +0x38d

goroutine 5 [chan receive]:
github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.init.0.func1()
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/bootstrap.go:50 +0x4c
created by github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse.init.0
        /home/abraithwaite/Projects/golang/src/github.com/segmentio/clickhouse-mon/vendor/github.com/kshvakov/clickhouse/bootstrap.go:47 +0x74

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [select]:
database/sql.(*DB).connectionOpener(0xc0000d0180, 0x87ffe0, 0xc00005c840)
        /usr/lib/go/src/database/sql/sql.go:1000 +0xe8
created by database/sql.OpenDB
        /usr/lib/go/src/database/sql/sql.go:670 +0x15e

goroutine 8 [select]:
database/sql.(*DB).connectionResetter(0xc0000d0180, 0x87ffe0, 0xc00005c840)
        /usr/lib/go/src/database/sql/sql.go:1013 +0xfb
created by database/sql.OpenDB
        /usr/lib/go/src/database/sql/sql.go:671 +0x194

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x45b2b0
rdx    0x80
rdi    0x4
rsi    0x7fffbeca0500
rbp    0x7fffbeca0b00
rsp    0x7fffbeca04c0
r8     0x0
r9     0x0
r10    0xffffffff
r11    0x202
r12    0x8
r13    0xfa
r14    0x86e200
r15    0x0
rip    0x45b2b0
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by abraithwaite** [comment]
This is a hacky patch that gets around the issue:

https://github.com/kshvakov/clickhouse/compare/master...segmentio:fix-alter-table

Could definitely be cleaned up.

**Comment by devoxel** [comment]
All partition quires that don't return data get this error (FREEZE in my case).

To workaround without a patch you can do `SETTINGS alter_partition_verbose_result = 1` in the query - really this shouldn't be required.

**Comment by abraithwaite** [comment]
By "this" you mean changing the setting shouldn't be required?  Because I agree :-)

Thanks for the less hacky workaround though!
