### ISSUE TITLE
Are LowCardinality(String) supported for (columnar) native ?

### ISSUE THREAD

**Issue by aadant** [ClickHouse/clickhouse-go#462]
### Issue description

My code similar to benchmarks v2  fails for me with LowCardinality(String)

```
panic: assignment to entry in nil map

goroutine 57 [running]:
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*LowCardinality).AppendRow(0xc00020c000, {0x86e2c0, 0xc0003c0020})
        /home/aadant/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.1/lib/column/lowcardinality.go:130 +0x1e5
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Append(0xc000190000, {0xc0001940a0, 0x5, 0x8})
        /home/aadant/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.1/lib/proto/block.go:42 +0x196
github.com/ClickHouse/clickhouse-go/v2.(*batch).Append(0xc0003ba230, {0xc0001940a0, 0xc0001a8000, 0xc00018e000})
        /home/aadant/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.1/conn_batch.go:62 +0x2a
```

columnar

```
panic: assignment to entry in nil map

goroutine 147 [running]:
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*LowCardinality).AppendRow(0xc005c3a000, {0x86e2a0, 0xc000494060})
        /home/aadant/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.1/lib/column/lowcardinality.go:130 +0x1e5
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*LowCardinality).Append(0xc005c3a000, {0x866580, 0xc0003b20d8})
        /home/aadant/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.1/lib/column/lowcardinality.go:104 +0x258
github.com/ClickHouse/clickhouse-go/v2.(*batchColumn).Append(0xc0002c86c0, {0x866580, 0xc0003b20d8})
        /home/aadant/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.1/conn_batch.go:125 +0x44
```

### Example code

Create a table with LowCardinality(String) instead of String in the benchmark

c1 Float64
c2 LowCardinality(String)
c3 LowCardinality(String)
c4 String
c5 UInt64

```
 conn, err := clickhouse.Open(&clickhouse.Options{
                        Addr: []string{target+":9000"},
                        Auth: clickhouse.Auth{
                                Database: database,
                                Username: user,
                                Password: password,
                        },
                    })
        checkErr(err)
        rowsInserted := 0

        query:= "INSERT INTO " + database + "." + table + "(c1,  c2, c3, c4, c5) VALUES(?, ?, ?, ?, ?)"
        {
            batch, err := conn.PrepareBatch(context.Background(), query)
            checkErr(err)
            for msg := range msgchan {
                        c1, _ := strconv.ParseFloat(msg.Time, 64)
                        err = batch.Append(
                                msg.c1,
                                msg.c2,
                                msg.c3,
                                msg.c4,
                                msg.c5,
                        )
                        rowsInserted++

                        checkErr(err)
                        if rowsInserted % block_size == 0 {
                                err= batch.Send()
                                checkErr(err)
                        }

            }
        err = batch.Send();
        checkErr(err)
        }
        counterchan <- rowsInserted

```

### Error log
```
If you have an error log, please paste it here.
```

### Configuration
*OS:*

*Interface:  `native`

Golang SQLDriver 1.1.54453

*Go version:* 

go version go1.17.6 linux/amd64

*ClickHouse Server version:*

21.8.11

**Comment by kshvakov** [comment]
Hi, LowCardinality supported for all interfaces and types. But you can send a batch only once. If you need to send multiple inserts, you must prepare each batch. 

Example 

```go 
var data []data
for msg := range msgchan {
    data=append(data)
    if len(data) % blockSize {
        sendBatch(data)
        data = data[:0]
    }
}

func sendBatch(data []data) {
  batch, err := conn.PrepareBatch(context.Background(), query)
  for _, v:= range data {
     batch.Append(v)
  }
  batch.Send()

}
```

**Comment by aadant** [comment]
Thank you, that was the issue. I would if there could be a better error message, rather than a crash.

**Comment by kshvakov** [comment]
@aadant done https://github.com/ClickHouse/clickhouse-go/commit/ed4aabed6b9aeb2f4458880ed74874b98dc371d0

**Comment by aadant** [comment]
@kshvakov thanks a lot, the fix looks good to me.
