### ISSUE TITLE
v2 Panics on Scan due to index out of range

### ISSUE THREAD

**Issue by gingerwizard** [ClickHouse/clickhouse-go#467]
### Issue description

The driver shouldn't panic with an index out of range whilst scanning.

### Example code

Will add

### Error log
```
panic: runtime error: index out of range [101] with length 101

goroutine 1 [running]:
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*String).Row(0x955840, 0xc013f49ec0, 0x0)
	/home/dale/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.3/lib/column/string.go:29 +0x77
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Map).row(0xc00012ff20, 0x2)
	/home/dale/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.3/lib/column/map.go:178 +0x14c
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Map).Row(0xc003c38558, 0x928b40, 0xa0)
	/home/dale/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.3/lib/column/map.go:53 +0x19
github.com/ClickHouse/clickhouse-go/v2.(*stdRows).Next(0xc00012c148, {0xc00024cfc0, 0x24, 0x203000})
	/home/dale/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.3/clickhouse_std.go:178 +0xe7
database/sql.(*Rows).nextLocked(0xc00002e780)
	/usr/local/go/src/database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	/usr/local/go/src/database/sql/sql.go:2945 +0x2f
database/sql.withLock({0xaa43f0, 0xc00002e7b0}, 0xc0000e7030)
	/usr/local/go/src/database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc00002e780)
	/usr/local/go/src/database/sql/sql.go:2944 +0x6f
```

### Configuration
*OS:* Linux - Ubuntu 20.04

*Interface:*   `database/sql`

*Driver version:* v2.0.0-beta.3

*Go version:* go1.17.6 linux/amd64

*ClickHouse Server version:* 21.12.3.32

**Comment by gingerwizard** [comment]
Working on getting a simple piece of code to reproduce this.

**Comment by gingerwizard** [comment]
A less than simple example, working on making it simpler


```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/ClickHouse/clickhouse-go/v2"
	"log"
	"reflect"
)

type DatabaseFrame struct {
	name        string
	ColumnNames []string
	rows        *sql.Rows
	columnTypes []*sql.ColumnType
	vars        []interface{}
}

func NewDatabaseFrame(name string, rows *sql.Rows) (DatabaseFrame, error) {
	databaseFrame := DatabaseFrame{}
	columnTypes, err := rows.ColumnTypes()
	if err != nil {
		return DatabaseFrame{}, err
	}
	databaseFrame.columnTypes = columnTypes
	databaseFrame.name = name
	vars := make([]interface{}, len(columnTypes), len(columnTypes))
	columnNames := make([]string, len(columnTypes), len(columnTypes))
	for i := range columnTypes {
		value := reflect.Zero(columnTypes[i].ScanType()).Interface()
		vars[i] = &value
		columnNames[i] = columnTypes[i].Name()
	}
	databaseFrame.ColumnNames = columnNames
	databaseFrame.vars = vars
	databaseFrame.rows = rows
	return databaseFrame, nil
}

func (f DatabaseFrame) Next() ([]interface{}, bool, error) {
	values := make([]interface{}, len(f.columnTypes), len(f.columnTypes))
	for f.rows.Next() {
		if err := f.rows.Scan(f.vars...); err != nil {
			return nil, false, err
		}
		for i := range f.columnTypes {
			ptr := reflect.ValueOf(f.vars[i])
			values[i] = ptr.Elem().Interface()
		}
		return values, true, nil
	}
	f.rows.Close()
	return nil, false, f.rows.Err()
}

func NewNativeClient(host string, port uint16, username string, password string) (*sql.DB, error) {
	// debug output ?debug=true
	connection, err := sql.Open("clickhouse", fmt.Sprintf("clickhouse://%s:%s@%s:%d/", username, password, host, port))
	if err != nil {
		return nil, err
	}
	if err := connection.Ping(); err != nil {
		return nil, err
	}
	return connection, nil
}

func ReadTableNamesForDatabase(connection *sql.DB, databaseName string) ([]string, error) {
	rows, err := connection.Query(fmt.Sprintf("SHOW TABLES FROM %s", databaseName))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tableNames []string
	var name string
	for rows.Next() {
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		tableNames = append(tableNames, name)
	}
	return tableNames, nil
}

func main() {
	c, err := NewNativeClient("localhost", 9000, "", "N050up4u@!")
	if err != nil {
		log.Fatal(err)
	}
	tables, err := ReadTableNamesForDatabase(c, "system")
	if err != nil {
		log.Println("Query failed on system table listing")
		log.Fatal(err)
	}
	i := 0
	breakOn := 100000
	for _, table := range tables {
		log.Printf("Reading system.%s", table)
		rows, err := c.Query(fmt.Sprintf("SELECT * FROM system.%s", table))
		if err != nil {
			log.Printf("Query failed for %s", table)
			log.Println(err)
			continue
		}
		frame, err := NewDatabaseFrame("db_frame", rows)
		if err != nil {
			log.Println("Cant' construct frame")
			log.Fatal(err)
		}
		//iterate to exhaustion

		for {
			_, ok, err := frame.Next()
			if !ok {
				if err != nil {
					log.Println("Failed on termination")
					log.Println(err)
					break
				}
				break
			}
			if err != nil {
				log.Fatal(err)
			}
			i++
			if i == breakOn {
				break
			}
		}
		log.Printf("Success with %d rows!!", i)
		i = 0
	}

}

```

**Comment by gingerwizard** [comment]
simplified above

**Comment by kshvakov** [comment]
@gingerwizard Fixed 

```
2022/01/26 15:37:35 Reading system.system.query_thread_log
2022/01/26 15:37:46 Success with 1150694 rows!!
```

**Comment by gingerwizard** [comment]
@kshvakov much faster than me!  was just about to propose something! :clap:

**Comment by gingerwizard** [comment]
Fixed for me. Great work @kshvakov and thanks for the fast response!
