### ISSUE TITLE
Panic: slice bound of range

### ISSUE THREAD

**Issue by simonenkoav** [ClickHouse/clickhouse-go#480]
### Issue description
Seems that there is a bug in the driver code.

### Example code
Saving data like this:
```go
import (
	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/google/uuid"
)

type Value struct {
	ID        uuid.UUID `ch:"id"`
	Name      string    `ch:"name"`
	CreatedAt time.Time `ch:"created_at"`
}

...
	batch, err := s.conn.PrepareBatch(ctx, "insert into my_table (id, name, created_at)")
	for i, v := range values {
		if err = batch.Append(v.ID, v.Name, v.CreatedAt); err != nil {
			return err
		}
	}
	batch.Send()
...
```

### Error log
```
clickhouse [process]: unexpected packet 161
panic: runtime error: slice bounds out of range [36349:36348]

goroutine 713421 [running]:
bufio.(*Reader).Read(0xc02f5d4000, {0xc03671514d, 0xdc0b, 0xc0001c0230})
	/usr/local/go/src/bufio/bufio.go:238 +0x2e5
io.ReadAtLeast({0xe94dc0, 0xc02f5d4000}, {0xc0366ca000, 0x4ff5c, 0x101039}, 0x4ff5c)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
github.com/ClickHouse/clickhouse-go/v2/lib/compress.(*Reader).readBlock(0xc003c1c060)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/lib/compress/compress_reader.go:95 +0x22f
github.com/ClickHouse/clickhouse-go/v2/lib/compress.(*Reader).Read(0xc003c1c060, {0xc002106030, 0x1, 0xa})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/lib/compress/compress_reader.go:55 +0xc6
io.ReadAtLeast({0xe95200, 0xc003c1c060}, {0xc002106030, 0x1, 0xa}, 0x1)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
github.com/ClickHouse/clickhouse-go/v2/lib/io.(*Stream).Read(0x0, {0xc002106030, 0x0, 0x8})
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/lib/io/stream.go:58 +0x3e
github.com/ClickHouse/clickhouse-go/v2/lib/binary.(*Decoder).ReadByte(0xc002106020)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/lib/binary/decoder.go:171 +0x37
encoding/binary.ReadUvarint({0xe95160, 0xc002106020})
	/usr/local/go/src/encoding/binary/varint.go:115 +0x82
github.com/ClickHouse/clickhouse-go/v2/lib/binary.(*Decoder).Uvarint(...)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/lib/binary/decoder.go:57
github.com/ClickHouse/clickhouse-go/v2/lib/proto.decodeBlockInfo(0xc047c9fd70)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/lib/proto/block.go:206 +0x2c
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Decode(0xc039a91100, 0xc0201cc000, 0x48cb6f)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/lib/proto/block.go:127 +0x45
github.com/ClickHouse/clickhouse-go/v2.(*connect).readData(0xc00213a000, 0x1, 0x1)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/conn.go:193 +0x128
github.com/ClickHouse/clickhouse-go/v2.(*connect).handle(0xc00213a000, 0x60, 0xc028e41170)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/conn_process.go:90 +0x1f8
github.com/ClickHouse/clickhouse-go/v2.(*connect).process(0xc00213a000, {0xeaca10, 0xc028e3e680}, 0x0)
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/conn_process.go:81 +0xaf
github.com/ClickHouse/clickhouse-go/v2.(*connect).query.func1()
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/conn_query.go:62 +0xb9
created by github.com/ClickHouse/clickhouse-go/v2.(*connect).query
	/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.0-beta.16/conn_query.go:58 +0x4b1
```

### Configuration
*OS:*
```
╰─λ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

*Interface:* E.g. `native`

*Driver version:* `v2.0.0-beta.16`

*Go version:* 
```
╰─λ go version
go version go1.17.2 linux/amd64
```

*ClickHouse Server version:*
```
SELECT version()

┌─version()─┐
│ 21.8.3.44 │
└───────────┘
```

**Comment by kshvakov** [comment]
@simonenkoav Try v2.0.3 , I think the problem was in the connection pool

**Comment by simonenkoav** [comment]
Updated to `v2.0.3`, will see.
It's just `go get github.com/ClickHouse/clickhouse-go/v2` that downloads  `v2.0.0-beta.16`.
