### ISSUE TITLE
Selecting nested column in a nested property causes a runtime panic  

### ISSUE THREAD

**Issue by emrekasg** [ClickHouse/clickhouse-go#483]
### Issue description
I tried to get rows from my_table with

```go
rows, err := components.ClickHouse.Query(context.TODO(), "SELECT steps.result FROM exdb.my_table LIMIT 1")
if err != nil {
    log.Fatal(err)
}
```
but had this error
```
panic: interface conversion: reflect.Type is nil, not *reflect.rtype

goroutine 1 [running]:
reflect.SliceOf({0x0, 0x0})
        /usr/local/go/src/reflect/type.go:2333 +0x375
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Array).parse(0xc0000be0a0, {0xc00001e0a0, 0x4c})
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/lib/column/array.go:62 +0x2b4
github.com/ClickHouse/clickhouse-go/v2/lib/column.Type.Column({0xc00001e0a0, 0x4c})
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/lib/column/column_gen.go:130 +0xfde
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Decode(0xc00002a040, 0x0, 0x0)
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/lib/proto/block.go:159 +0x21d
github.com/ClickHouse/clickhouse-go/v2.(*connect).readData(0xc00007c000, 0x1, 0x1)
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/conn.go:197 +0x128
github.com/ClickHouse/clickhouse-go/v2.(*connect).firstBlock(0xc00007c000, {0x13114d0, 0xc0000aa008}, 0xc0000e8420)
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/conn_process.go:51 +0xee
github.com/ClickHouse/clickhouse-go/v2.(*connect).query(0xc00007c000, {0x13114d0, 0xc0000aa008}, 0xc000236030, {0x12bdf23, 0x3a}, {0x0, 0x0, 0x0})
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/conn_query.go:49 +0x38b
github.com/ClickHouse/clickhouse-go/v2.(*clickhouse).Query(0xc0000d06c0, {0x13114d0, 0xc0000aa008}, {0x12bdf23, 0x3a}, {0x0, 0x0, 0x0})
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/clickhouse.go:115 +0xd3
github.com/testgenielabs/test_results_v1/app.RunApp()
        /Users/emrekasgur/Desktop/testgenie/v1/test_results/app/app.go:23 +0x4f
main.main()
        /Users/emrekasgur/Desktop/testgenie/v1/test_results/main.go:6 +0x17
exit status 2
```
When I try the query with DataGrid it works fine but not with this driver.

I already know I can get rid of this panic by changing the query from "SELECT steps.result" to "SELECT steps.result[1]" 

But I think it shouldn't give this error

### Table schema: 
```sql
create table my_table
(
    example_id int,
    steps Nested(
          duration int,
          result Nested(
                duration UInt64,
                error_message Nullable(String),
                status UInt8
            ),
          keyword String
        ),
    status UInt8
)
engine = MergeTree()    
```

### Configuration
*OS:* MacOS Monterey/12.0 Beta

*Interface:* `native`

*Driver version:* latest/v2

*Go version:* go1.17.6 darwin/amd64

*ClickHouse Server version:* 22.2.1.3279

**Comment by emrekasg** [comment]
Also, "SELECT *" panics too in the same table

**Comment by kshvakov** [comment]
@emrekasg Yes. Nested data types are not supported because I do not know how to represent them in go types, you have to pass all the component column arrays of a nested data structure separately. I have added an error message.

**Comment by emrekasg** [comment]
@kshvakov thank you for your quick response. So, I wonder how we can insert a nested array.
```go
batch, err := components.ClickHouse.PrepareBatch(context.TODO(), "INSERT INTO exdb.my_table (example_id, steps.duration, steps.keyword, steps.result, status) VALUES (?, ?, ?, ?, ?)")
if err != nil {
    fmt.Println(err)
}
batch.Append(1, "feature_name", 1, "passed", [][]interface{}{{uint64(4), "error", uint8(1)}}, 1) // go already exists when PrepareBatch runned, this line will not work
batch.Send()

```
Error log: 
```
exit status 2
[clickhouse][conn=1][127.0.0.1:9000][handshake] -> Golang SQLDriver 1.1.54453
[clickhouse][conn=1][127.0.0.1:9000][handshake] <- ClickHouse (emres-macbook-pro.local) server version 22.2.1 revision 54455 (timezone Europe/Istanbul)
[clickhouse][conn=1][127.0.0.1:9000][send query] compression=true INSERT INTO testgenie.example (project_id, steps.duration, steps.result) VALUES
[clickhouse][conn=1][127.0.0.1:9000][send data] compression=true
[clickhouse][conn=1][127.0.0.1:9000][table columns]
Nested data type is not supported. You should pass all the component column arrays of a nested data structure separately
<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x123aedd]

goroutine 1 [running]:
github.com/ClickHouse/clickhouse-go/v2.(*batch).Append(0xc00000e150, {0xc00007a410, 0x1, 0x1})
        /Users/emrekasgur/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.7/conn_batch.go:78 +0x1d
github.com/testgenielabs/test_results_v1/app/models.CreateTestResult()
        /Users/emrekasgur/Desktop/testgenie/v1/test_results/app/models/TestResults.go:50 +0x3a9
github.com/testgenielabs/test_results_v1/app/models.init.0()
        /Users/emrekasgur/Desktop/testgenie/v1/test_results/app/models/TestResults.go:33 +0x17
exit status 2

```


Even this go driver doesn't support nested arrays, it's a feature of ClickHouse. Is there a way to insert that?

**Comment by kshvakov** [comment]
Driver doesn't  support multidimensional Nested columns as Array.  Now there is an ambiguous behavior on the server side, example 

```
INSERT INTO example (steps.result.duration) FORMAT Values

>> DB::Exception: No such column steps.result.duration in table default.example
```

but 

```

SELECT steps.result.duration
FROM example

Ok.
```

**Comment by emrekasg** [comment]
OK. As far as I understand, the only way to add nested is to insert it as string instead of []interface.

**Comment by kshvakov** [comment]
Multidimensional Nested data types is a ClickHouse feature. I'll think about Go API design.

**Comment by kshvakov** [comment]
@emrekasg Nested data types added in V2.0.9. See [example](https://github.com/ClickHouse/clickhouse-go/blob/v2/tests/nested_test.go#L11)

**Comment by emrekasg** [comment]
I tried it and it works great. I think the issue is solved. Thank you very much

**Comment by Recodify** [comment]
@kshvakov Is this nested structure support only available via the `native`/`clickhouse` interface, or is it possible with the `database/sql` interface too?
