### ISSUE TITLE
conn.Close() will panic on invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by d-bytebase** [ClickHouse/clickhouse-go#484]
### Issue description
Tell us what should happen and what happens instead

### Example code
```go
package main

import (
	"fmt"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
)

func main() {
	conn := clickhouse.OpenDB(&clickhouse.Options{
		Addr: []string{"127.0.0.1:9000"},
		Auth: clickhouse.Auth{
			Database: "default",
			Username: "default",
			Password: "",
		},
		Settings: clickhouse.Settings{
			"max_execution_time": 60,
		},
		DialTimeout: 5 * time.Second,
		Compression: &clickhouse.Compression{
			clickhouse.CompressionLZ4,
		},
		//Debug: true,
	})
	if err := conn.Ping(); err != nil {
		fmt.Printf("1: %v\n", err)
	}
	row := conn.QueryRow("SELECT 1")
	var one int
	if err := row.Scan(&one); err != nil {
		fmt.Printf("2: %v\n", err)
	}
	fmt.Printf("3: %v\n", one)
	if err := conn.Close(); err != nil {
		fmt.Printf("4: %v\n", err)
	}
	fmt.Printf("5\n")
}
```

### Error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x70 pc=0x104d9b730]

goroutine 1 [running]:
github.com/ClickHouse/clickhouse-go/v2.(*connect).close(0x0)
	/Users/xx/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/conn.go:139 +0x20
github.com/ClickHouse/clickhouse-go/v2.(*stdDriver).Close(0x1400007ab40)
	/Users/xx/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.6/clickhouse_std.go:176 +0x2c
database/sql.(*DB).Close(0x1400007cf70)
	/opt/homebrew/Cellar/go/1.17.6/libexec/src/database/sql/sql.go:911 +0x3e0
main.main()
	/Users/xx/src/clicktest/main.go:36 +0x40c
exit status 2
```

### Configuration
*OS:* macos

*Interface:* E.g. `native`, `database/sql`
database/sql

*Driver version:*
2.0.6

*Go version:* run `go version` in your console
go version go1.17.6 darwin/arm64

*ClickHouse Server version:*
22

**Comment by kshvakov** [comment]
Fixed

**Comment by d-bytebase** [comment]
Thanks kshvakov@ for the quick fix!

**Comment by d-bytebase** [comment]
This closes the Clickhouse related issue in Bytebase for doing schema update changes https://github.com/bytebase/bytebase/issues/543

Thanks!
