### ISSUE TITLE
It's not possible to check if driver.Batch is nil when PrepareBatch errors

### ISSUE THREAD

**Issue by also1366** [ClickHouse/clickhouse-go#578]
### Issue description
I try to check whether driver.Batch is nil, and run Abort if it's not. But program panics, because underlying pointer is nil. So what's happening is conn.prepareBatch() returns *driver.batch(nil), and PrepareBatch() propagates it as driver.Batch(*driver.batch(nil))
```go
// how it's now
func (ch *clickhouse) PrepareBatch(ctx context.Context, query string) (driver.Batch, error) {
	conn, err := ch.acquire(ctx)
	if err != nil {
		return nil, err
	}
	return conn.prepareBatch(ctx, query, ch.release)
}

// AFAIK, it should be
func (ch *clickhouse) PrepareBatch(ctx context.Context, query string) (driver.Batch, error) {
	conn, err := ch.acquire(ctx)
	if err != nil {
		return nil, err
	}
	conn, err = conn.prepareBatch(ctx, query, ch.release)
	if err != nil {
		return nil, err
	}
	return conn, nil
}
```

### Example code
```go
package main

import (
	"context"
	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"log"
)

func main() {
	ctx := context.Background()
	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr:  []string{"127.0.0.1:9000"},
		Debug: true,
	})
	if err != nil {
		// by the way, clickhouse.Open never returns an error
		log.Fatal(err)
	}

	err = execInBatch(conn, ctx)
	if err != nil {
		// won't reach here
		log.Fatal(err)
	}
}

func execInBatch(conn driver.Conn, ctx context.Context) (err error) {
	var batch driver.Batch
	defer func() {
		if batch != nil { // the check doesn't work
			log.Println(batch) // prints <nil>
			_ = batch.Abort()  // panics with nil pointer
		}
	}()

	batch, err = conn.PrepareBatch(ctx, "INSERT INTO non_existent_table")
	if err != nil {
		// return with error
		return err
	}
	panic("should not be reached, as we get an error")
}
```

### Error log
```
[clickhouse][conn=1][127.0.0.1:9034][handshake] -> Golang SQLDriver 1.1.54453
[clickhouse][conn=1][127.0.0.1:9034][handshake] <- ClickHouse (d1f1e9bfeda5) server version 22.4.5 revision 54455 (timezone UTC)
[clickhouse][conn=1][127.0.0.1:9034][send query] compression=false INSERT INTO non_existent_table VALUES
[clickhouse][conn=1][127.0.0.1:9034][send data] compression=false
[clickhouse][conn=1][127.0.0.1:9034][exception] code: 60, message: Table default.non_existent_table doesn't exist
2022/05/13 10:33:41 <nil>
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5d7418]

goroutine 1 [running]:
github.com/ClickHouse/clickhouse-go/v2.(*batch).Abort.func1()
        /home/alex/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.14/conn_batch.go:80 +0x18
panic({0x5fcd40, 0x7d76d0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/ClickHouse/clickhouse-go/v2.(*batch).Abort(0xc000203e88)
        /home/alex/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.0.14/conn_batch.go:83 +0x55
main.execInBatch.func1()
        /home/alex/projects/bugexample/example.go:33 +0x67
main.execInBatch({0x683b48, 0xc00006a6e0}, {0x67ff90, 0xc0000220e0})
        /home/alex/projects/bugexample/example.go:40 +0xc2
main.main()
        /home/alex/projects/bugexample/example.go:21 +0xe5
```

### Configuration
*OS:* Debian GNU/Linux 11 (bullseye)

*Interface:* native

*Driver version:* v2.0.14

*Go version:* go version go1.17.6 linux/amd64

*ClickHouse Server version:* 22.4.5.9

**Comment by gingerwizard** [comment]
thanks @also1366 for this

`PrepareBatch` is returning an interface holding a nil value - hence its not actually nil. For it to be nil, the type also needs to be nil. Now you could do 

```
	if !reflect.ValueOf(batch).IsNil() {
              batch.Abort()
```

But yeh this is unreasonable and a bad pattern. We will fix.

**Comment by gingerwizard** [comment]
I believe https://github.com/ClickHouse/clickhouse-go/issues/578 provides an acceptable fix. Thanks again @also1366 for reporting.

**Comment by also1366** [comment]
@gingerwizard, hey, thank you very much for a quick fix. I looked at #580, and I would rather make
```go
	if batch != nil {
		assert.Fail(t, "should not be nil")
	}
```
I think that would make test more apparent and clean.
But thanks anyway
