### ISSUE TITLE
Panic when query empty map nested with map 

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/clickhouse-go#692]
### Issue description
Panic when query empty map nested with map  

### Example code
```go
package std

import (
	"database/sql"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestStdMap(t *testing.T) {
	if conn, err := sql.Open("clickhouse", "clickhouse://127.0.0.1:9000"); assert.NoError(t, err) {
		if err := checkMinServerVersion(conn, 21, 9, 0); err != nil {
			t.Skip(err.Error())
			return
		}
		const ddl = `
		CREATE TABLE test_map (
			  Col1 Map(String, UInt64)
			, Col2 Map(String, UInt64)
			, Col3 Map(String, UInt64)
			, Col4 Array(Map(String, String))
			, Col5 Map(LowCardinality(String), LowCardinality(UInt64))
			, Col6 Map(String, Map(String, Int64))
		) Engine Memory
		`
		/*
			defer func() {
				conn.Exec("DROP TABLE test_map")
			}()
		*/
		if _, err := conn.Exec(ddl); assert.NoError(t, err) {
			scope, err := conn.Begin()
			if !assert.NoError(t, err) {
				return
			}
			if batch, err := scope.Prepare("INSERT INTO test_map"); assert.NoError(t, err) {
				var (
					col1Data = map[string]uint64{
						"key_col_1_1": 1,
						"key_col_1_2": 2,
					}
					col2Data = map[string]uint64{
						"key_col_2_1": 10,
						"key_col_2_2": 20,
					}
					col3Data = map[string]uint64{}
					col4Data = []map[string]string{
						map[string]string{"A": "B"},
						map[string]string{"C": "D"},
					}
					col5Data = map[string]uint64{
						"key_col_5_1": 100,
						"key_col_5_2": 200,
					}
					col6Data = map[string]map[string]int64{}
				)
				if _, err := batch.Exec(col1Data, col2Data, col3Data, col4Data, col5Data, col6Data); assert.NoError(t, err) {
					if assert.NoError(t, scope.Commit()) {
						var (
							col1 interface{}
							col2 map[string]uint64
							col3 map[string]uint64
							col4 []map[string]string
							col5 map[string]uint64
							col6 map[string]map[string]int64
						)
						if err := conn.QueryRow("SELECT * FROM test_map").Scan(&col1, &col2, &col3, &col4, &col5, &col6); assert.NoError(t, err) {
							assert.Equal(t, col1Data, col1)
							assert.Equal(t, col2Data, col2)
							assert.Equal(t, col3Data, col3)
							assert.Equal(t, col4Data, col4)
							assert.Equal(t, col5Data, col5)
						}
					}
				}
			}
		}
	}
}

```

### Error log
```
panic: runtime error: index out of range [-1]

goroutine 16 [running]:
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Map).Decode(0xc0000fe680, 0xc0000fe680?, 0x0?)
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/lib/column/map.go:147 +0xac
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*Map).Decode(0xc0000fe600, 0x731918?, 0xc0000fe600?)
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/lib/column/map.go:151 +0x93
github.com/ClickHouse/clickhouse-go/v2/lib/proto.(*Block).Decode(0xc000118000, 0x0?, 0x0?)
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/lib/proto/block.go:173 +0x2a2
github.com/ClickHouse/clickhouse-go/v2.(*connect).readData(0xc000338000, 0x1, 0x1)
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/conn.go:190 +0x10b
github.com/ClickHouse/clickhouse-go/v2.(*connect).handle(0xc000338000, 0x48?, 0xc0000ca8a0)
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/conn_process.go:89 +0x1fe
github.com/ClickHouse/clickhouse-go/v2.(*connect).process(0xc000338000, {0x730498, 0xc0000180f0}, 0x0?)
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/conn_process.go:80 +0x7f
github.com/ClickHouse/clickhouse-go/v2.(*connect).query.func1()
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/conn_query.go:65 +0xc5
created by github.com/ClickHouse/clickhouse-go/v2.(*connect).query
        /data1/liyang/goproject/pkg/mod/git.sysop.bigo.sg/bigdata/clickhouse-go/v2@v2.0.0-20220725034349-26bf59bb7fc2/conn_query.go:61 +0x55b
exit status 2
```

### Configuration
*OS:* Linux Ubuntu20.4 
*Interface:*  `database/sql`

*Driver version:* v2.2.0 

*Go version:* go version go1.18.1 linux/amd64

*ClickHouse Server version:* v21.10

**Comment by gingerwizard** [comment]
Looks like an urgent bug, will fix asap.

**Comment by gingerwizard** [comment]
Next release - 31st. Thanks for reporting @taiyang-li
