### ISSUE TITLE
Batch.Send panics if AppendStruct couldn't map Enum

### ISSUE THREAD

**Issue by JILeXanDR** [ClickHouse/clickhouse-go#703]
### Issue description
When I set wrong value for Enum I logged that error and didn't expect that sending will fail with panic.

### Example code
```go
batch, _ := conn.PrepareBatch(ctx, "INSERT INTO requests")

if err := batch.AppendStruct(&request); err != nil {
    // Here I caught an error:
    // clickhouse [AppendRow]: (format Enum8('Get' = 0, 'Post' = 1)) unknown element \"get\""
}

_ = batch.Send() // It panics here
```

### Error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ddaa9a]

goroutine 49 [running]:
github.com/ClickHouse/clickhouse-go/v2/lib/binary.(*Encoder).UInt8(0x0, 0x2)
        /Users/alexandr/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.2.0/lib/binary/encoder.go:72 +0x5a
github.com/ClickHouse/clickhouse-go/v2/lib/binary.(*Encoder).Byte(0x0, 0x2)
        /Users/alexandr/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.2.0/lib/binary/encoder.go:52 +0x4f
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendData(0xc0003bc540, 0xc0003a4d00, {0x0, 0x0})
        /Users/alexandr/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.2.0/conn.go:166 +0x229
github.com/ClickHouse/clickhouse-go/v2.(*batch).Send(0xc000142410)
        /Users/alexandr/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.2.0/conn_batch.go:140 +0x347
```

### Configuration
*OS:* `MacOS`

*Interface:* `native`

*Driver version:* `2.2.0`

*Go version:* `1.18.3`

*ClickHouse Server version:* `22.1.3.7`

**Comment by gingerwizard** [comment]
Shouldn't panic ever. Will patch asap. Thanks for reporting.

**Comment by gingerwizard** [comment]
Ok, so here is a test - in summary, the you can't call `Send()` on a batch where an `Append` has failed. It invalidates the batch since it [releases the connection](https://github.com/ClickHouse/clickhouse-go/blob/main/conn_batch.go#L89-L103). This is the case should any batch append fail. This ties into https://github.com/ClickHouse/clickhouse-go/issues/655 - but raises other questions. Will broaden the scope of this ticket.

```
func Test703(t *testing.T) {
	var (
		ctx       = context.Background()
		conn, err = clickhouse.Open(&clickhouse.Options{
			Addr: []string{"127.0.0.1:9000"},
			Auth: clickhouse.Auth{
				Database: "default",
				Username: "default",
				Password: "",
			},
		})
	)
	require.NoError(t, err)
	conn.Exec(ctx, "DROP TABLE test_enum")
	const ddl = `CREATE TABLE test_enum (
				Col1 Enum8 ('Click'=5, 'House'=25)
			) Engine Memory`
	require.NoError(t, conn.Exec(ctx, ddl))

	defer func() {
		conn.Exec(ctx, "DROP TABLE test_enum")
	}()
	batch, err := conn.PrepareBatch(ctx, "INSERT INTO test_enum")
	require.NoError(t, err)
	type request struct {
		Col1 string
	}
	assert.NoError(t, batch.AppendStruct(&request{
		Col1: "house",
	}))
	require.NoError(t, batch.Send())
}
```
