### ISSUE TITLE
Error batch inserting array of named tuple

### ISSUE THREAD

**Issue by ryoid** [ClickHouse/clickhouse-go#812]
### Issue description
Batch inserting arrays of named tuples does not work.

### Example code

Referencing from the [tuple test case](https://github.com/ClickHouse/clickhouse-go/blob/850295602f90b528c106ee28df410d53b387889d/examples/clickhouse_api/tuple.go)

Add `Col4` (Array of Col1)
```sql
CREATE TABLE example (
	Col1 Tuple(name String, age UInt8),
	Col2 Tuple(String, UInt8),
	Col3 Tuple(name String, id String),
	Col4 Array(Tuple(name String, age UInt8)),
) 
Engine Memory
```

```go
batch.Append(
  map[string]interface{}{"name": "Clicky McClickHouse Jnr", "age": uint8(20)},
  []interface{}{"Baby Clicky McClickHouse", uint8(1)},
  map[string]string{"name": "Geoff", "id": "12123"},
  // Col4
  []interface{}{
    map[string]interface{}{"name": "Clicky McClickHouse Jnr", "age": uint8(20)},
  },
)
```
I tried unnamed tuple array (`Col4 Array(Tuple(String, UInt8))`) and there were no issues.

### Error log
```
clickhouse: expected 5 arguments, got 4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10311d660]

goroutine 98 [running]:
github.com/ClickHouse/ch-go/proto.(*Buffer).PutUInt8(...)
	/Users/ryoid/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:97
github.com/ClickHouse/ch-go/proto.(*Buffer).PutByte(...)
	/Users/ryoid/go/pkg/mod/github.com/!click!house/ch-go@v0.47.3/proto/buffer.go:82
github.com/ClickHouse/clickhouse-go/v2.(*connect).sendData(0x1400072cb60, 0x140005589c0?, {0x0, 0x0})
	/Users/ryoid/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn.go:171 +0xa0
github.com/ClickHouse/clickhouse-go/v2.(*batch).Send(0x140006b7bd0)
	/Users/ryoid/go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.3.0/conn_batch.go:148 +0xf4
```

### Configuration
*OS:* `macos 12.0` (ClickHouse ran in Docker)
*Interface:* `native`
*Driver version:* `github.com/ClickHouse/clickhouse-go/v2 v2.3.0`
*Go version:* `1.19 darwin/arm64`
*ClickHouse Server version:* `22.9.3.18`

Edit:
Not sure if this is an issue, realised this is possible by splitting the values.

```go
batch.Append(
  map[string]interface{}{"name": "Clicky McClickHouse Jnr", "age": uint8(20)},
  []interface{}{"Baby Clicky McClickHouse", uint8(1)},
  map[string]string{"name": "Geoff", "id": "12123"},
  // Col4
  []interface{}{"Clicky McClickHouse Jnr"},
  []interface{}{uint8(20)},
)
```

**Comment by gingerwizard** [comment]
This is an interesting one @ryoid When we create an `Array(Tuple` in ClickHouse actually creates

```

SHOW CREATE TABLE test_812

Query id: 7e33b750-2d90-4fc5-a9b2-465d87d89c1d

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE `clickhouse-go-issues-6a78c40e-623-1668871134508`.test_812
(
    `Col1` Tuple(name String, age UInt8),
    `Col2` Tuple(String, UInt8),
    `Col3` Tuple(name String, id String),
    `Col4.name` Array(String),
    `Col4.age` Array(UInt8)
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec.
```

hence when we to `Prepare` and ask to do an insert, the native protocols asks for 5 columns. This is only the case on named tuples.

Now an `Array(Tuple` is actually just a [Nested](https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested/#nestedname1-type1-name2-type2-) type

e.g. 
if I create

```
	require.NoError(t, err)
	const ddl = `
		CREATE TABLE test_812 (
			Col1 Tuple(name String, age UInt8),
			Col2 Tuple(String, UInt8),
			Col3 Tuple(name String, id String),
			Col4 Nested(name String, age UInt8)
		) Engine MergeTree() ORDER BY tuple()
		`
	defer func() {
		conn.Exec(ctx, "DROP TABLE IF EXISTS test_812")
	}()
	conn.Exec(ctx, "DROP TABLE IF EXISTS test_812")
```

I also get

```
clickhouse :) SHOW CREATE TABLE test_812

SHOW CREATE TABLE test_812

Query id: a7323e92-0a06-42a5-b07c-cec52b40b8de

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE `clickhouse-go-issues-c2cebf8b-805-1668871299255`.test_812
(
    `Col1` Tuple(name String, age UInt8),
    `Col2` Tuple(String, UInt8),
    `Col3` Tuple(name String, id String),
    `Col4.name` Array(String),
    `Col4.age` Array(UInt8)
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

To solve this we have to set `"flatten_nested": 0,` - see [](https://clickhouse.com/docs/en/operations/settings/settings#flatten-nested). In fact the exact example is there.

This conveniently works if you specify `Nested` or `Array(Tuple`. The following passes

```
func Test812(t *testing.T) {
	var (
		conn, err = clickhouse_tests.GetConnection("issues", clickhouse.Settings{
			"max_execution_time": 60,
			"flatten_nested":     0,
		}, nil, &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		})
	)
	ctx := context.Background()
	require.NoError(t, err)
	const ddl = `
		CREATE TABLE test_812 (
			Col1 Tuple(name String, age UInt8),
			Col2 Tuple(String, UInt8),
			Col3 Tuple(name String, id String),
			Col4 Array(Tuple(name String, age UInt8))
		) Engine MergeTree() ORDER BY tuple()
		`
	defer func() {
		conn.Exec(ctx, "DROP TABLE IF EXISTS test_812")
	}()
	conn.Exec(ctx, "DROP TABLE IF EXISTS test_812")
	require.NoError(t, conn.Exec(ctx, ddl))
	batch, err := conn.PrepareBatch(ctx, "INSERT INTO test_812")
	require.NoError(t, batch.Append(
		map[string]interface{}{"name": "Clicky McClickHouse Jnr", "age": uint8(20)},
		[]interface{}{"Baby Clicky McClickHouse", uint8(1)},
		map[string]string{"name": "Geoff", "id": "12123"},
		// Col4
		[]interface{}{
			map[string]interface{}{"name": "Clicky McClickHouse Jnr", "age": uint8(20)},
		},
	))
	require.NoError(t, batch.Send())
}
```

Thanks for raising this. Its not obvious behaviour and we actually test it https://github.com/ClickHouse/clickhouse-go/blob/main/tests/nested_test.go#L66 - note the test comment.

**Comment by gingerwizard** [comment]
I'll close but raise a PR with simple test.

**Comment by ryoid** [comment]
> I'll close but raise a PR with simple test.

Thanks for the insightful response. A simple test will definitely be great, wasn't very intuitive to me since the unnamed tuple worked.
