### ISSUE TITLE
Client times out when a string is inserted into a UInt64

### ISSUE THREAD

**Issue by javier-sanz** [ClickHouse/clickhouse-go#88]
I have this field on a table `ClientVersion UInt64,`. When inserting on a table a made a mistake and I inserted the number being a go `string` without converting it. Doing that test timed out with the next stacktrace:

```
testing.startAlarm.func1()
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/Cellar/go/1.9.3/libexec/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 1 minutes]:
testing.(*T).Run(0xc42017c0f0, 0x44c46d4, 0x24, 0x44d2f08, 0x407cb06)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc42017c0f0)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc42017c0f0, 0xc42010bde0)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0xd0
testing.runTests(0xc420197060, 0x472aca0, 0xc, 0xc, 0x2)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420055f18, 0xc42010bf70)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:921 +0x111
main.main()
	wrkr-infix/subprocessor/_test/_testmain.go:66 +0xdb

goroutine 6 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc42016f720)
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:871 +0x53
created by database/sql.Open
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:609 +0x1ee

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x4b9ef70, 0x72, 0x0)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420178118, 0x72, 0xffffffffffffff00, 0x46f5340, 0x46f15b8)
	/usr/local/Cellar/go/1.9.3/libexec/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420178118, 0xc420608000, 0x400000, 0x400000)
	/usr/local/Cellar/go/1.9.3/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420178100, 0xc420608000, 0x400000, 0x400000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.3/libexec/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc420178100, 0xc420608000, 0x400000, 0x400000, 0x4070265, 0x4, 0x3)
	/usr/local/Cellar/go/1.9.3/libexec/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4201bc000, 0xc420608000, 0x400000, 0x400000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.3/libexec/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc42017a0c0, 0xc4200ec550, 0x1, 0xa, 0xc420106f58, 0x4170952, 0xc420178100)
	/usr/local/Cellar/go/1.9.3/libexec/src/bufio/bufio.go:213 +0x30b
wrkr-infix/vendor/github.com/kshvakov/clickhouse.(*connect).Read(0xc42013a060, 0xc4200ec550, 0x1, 0xa, 0x41815bd, 0xc420178100, 0xc4201d6000)
	/Users/jsanz/Projects/goWorkspace/src/wrkr-infix/vendor/github.com/kshvakov/clickhouse/connect.go:95 +0x8e
wrkr-infix/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).ReadByte(0xc4200ec540, 0x0, 0x0, 0x438d041)
	/Users/jsanz/Projects/goWorkspace/src/wrkr-infix/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:143 +0x54
encoding/binary.ReadUvarint(0x46f4200, 0xc4200ec540, 0x108, 0x1000, 0x108)
	/usr/local/Cellar/go/1.9.3/libexec/src/encoding/binary/varint.go:110 +0x7b
wrkr-infix/vendor/github.com/kshvakov/clickhouse/lib/binary.(*Decoder).Uvarint(0xc4200ec540, 0x44d2cd8, 0xc420107060, 0x0)
	/Users/jsanz/Projects/goWorkspace/src/wrkr-infix/vendor/github.com/kshvakov/clickhouse/lib/binary/decoder.go:29 +0x37
wrkr-infix/vendor/github.com/kshvakov/clickhouse.(*clickhouse).process(0xc42016c090, 0x0, 0x0)
	/Users/jsanz/Projects/goWorkspace/src/wrkr-infix/vendor/github.com/kshvakov/clickhouse/clickhouse.go:227 +0x44
wrkr-infix/vendor/github.com/kshvakov/clickhouse.(*clickhouse).Commit(0xc42016c090, 0x0, 0x0)
	/Users/jsanz/Projects/goWorkspace/src/wrkr-infix/vendor/github.com/kshvakov/clickhouse/clickhouse.go:149 +0x241
database/sql.(*Tx).Commit.func1()
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:1788 +0x3c
database/sql.withLock(0x46f5fc0, 0xc420102000, 0xc420107218)
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:2873 +0x65
database/sql.(*Tx).Commit(0xc420178000, 0x9, 0xbe9779e0228bc108)
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:1787 +0x119
wrkr-infix/subprocessor.TestDataUsageEventPerPacketProcessor(0xc42017c1e0)
	/Users/jsanz/Projects/goWorkspace/src/wrkr-infix/subprocessor/dataUsageEvent_test.go:41 +0x98f
testing.tRunner(0xc42017c1e0, 0x44d2f08)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:789 +0x2de

goroutine 11 [select, 1 minutes]:
database/sql.(*Rows).awaitDone(0xc4200a6000, 0x46f87c0, 0xc42015a0c0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:2432 +0x107
created by database/sql.(*Rows).initContextClose
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:2420 +0x9c

goroutine 34 [chan receive]:
database/sql.(*Tx).awaitDone(0xc420178000)
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:1695 +0x4b
created by database/sql.(*DB).beginDC
	/usr/local/Cellar/go/1.9.3/libexec/src/database/sql/sql.go:1451 +0x216
FAIL	wrkr-infix/subprocessor	60.042s
```
When I converted the string to unit64 on go everything went smoothly. I am using version `v1.3.1-1-g95e4a6a`

**Comment by kshvakov** [comment]
Please, create small example to reproducing this problem

**Comment by javier-sanz** [comment]
I haven't been able to reproduce in a simple test. The next [code](https://github.com/javier-sanz/clickhouseGoDriverIssue88) tests the same situation but it does not hangs there forever. Instead I get the next error on the client:

```
code: 101, message: Unexpected packet Hello received from client
```

And on Clickhouse log
```
2018.02.10 09:25:02.027926 [ 3 ] <Debug> executeQuery: (from 172.17.0.1:38078, query_id: 4e427f5e-ca52-4ac1-88a2-915a6f703214) INSERT INTO default.test  (EventDate, Value) VALUES
2018.02.10 09:25:02.040773 [ 3 ] <Error> executeQuery: Code: 101, e.displayText() = DB::Exception: Unexpected packet Hello received from client, e.what() = DB::Exception (from 172.17.0.1:38078) (in query: INSERT INTO default.test  (EventDate, Value) VALUES), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x3419e66]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x14f2a9f]
2. /usr/bin/clickhouse-server(DB::TCPHandler::receivePacket()+0x146) [0x14fe146]
3. /usr/bin/clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x16a) [0x14fe52a]
4. /usr/bin/clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x274) [0x14ff244]
5. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x6ab) [0x14ffa7b]
6. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x150055b]
7. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x3ae7c5f]
8. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xad) [0x3aecead]
9. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x86) [0x3a1bad6]
10. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x39facf8]
11. /usr/bin/clickhouse-server() [0x4290b0f]
12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f906d3876ba]
13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f906c9a83dd]
```

Hope that helps.

**Comment by javier-sanz** [comment]
This Happens to me from time to time when adding new stuff I mess up with queries and fields. Any progress?

**Comment by kshvakov** [comment]
Fixed
